paths:
  image_directory: "/mnt/d/davos_1/11-17_1-57-46/" # 11-17_2-29-24
  output_directory: "/mnt/d/snowflake_analysis_plots"

constants:
  pixel_size: 5.86 # micrometers per pixel
  gravity: 9.81 # m/s^2 (not used currently)

plot:
  enable: true
  save: true
  display:
    matplotlib: false
    cv2_ellipses: false
    display_time: 1 # ms
  max_display_area: 10000 # pixels

debug:
  enabled: false
  show_intermediate_images: false

verbose:
  enabled: false

preprocessing:
  thresholding:
    method: "otsu" # options: "fixed", "otsu"
    value: 50
  sobel_detector:
    kernel_size: 3
  laplace_detector:
    kernel_size: 3
  gaussian_blur:
    kernel_size: 7 # 5
    sigma: 2.0
  morphology:
    opening:
      kernel_size: 3
      iterations: 2
    erode:
      kernel_size: 3
      iterations: 2
    dilate:
      kernel_size: 3
      iterations: 2

analysis:
  gaussian_blur:
    kernel_size: 7 # 5
    sigma: 2.0
  flake_sharp_angle_thresh: 300 # pixels
  sobel_detector:
    kernel_size: 3
  morphology:
    opening:
      kernel_size: 3
      iterations: 2
    closing:
      kernel_size: 20
      iterations: 3
    erode:
      kernel_size: 3
      iterations: 2
    dilate:
      kernel_size: 3
      iterations: 2
  thresholding:
    method: "fixed" # options: "fixed", "otsu"
    value: 20
  remove_small_objects:
    enabled: true
    small_object_size: 70 # pixels
  regionprops:
    min_area: 50 # pixels
  contour_filtering:
    min_area: 100 # pixels
  find_contour_level: .5

metrics:
  metrics:
    [
      "centroid",
      "centroid_local",
      "axis_major_length",
      "axis_minor_length",
      "orientation",
      "equivalent_diameter_area",
      "area",
      "area_convex",
      "perimeter",
      "feret_diameter_max",
      "solidity",
    ]
  # metrics:
  #   [
  #     "centroid_x",
  #     "centroid_y",
  #     "axis_major_length",
  #     "axis_minor_length",
  #     "orientation_rad",
  #     "aspect_ratio",
  #     "diameter_um",
  #     "complexity",
  #     "area_um2",
  #     "perimeter_um",
  #     "solidity",
  #   ]
  snr_ddof: 0
  stats:
    [
      "min_intensity",
      "max_intensity",
      "mean_intensity",
      "std_intensity",
      "variance_intensity",
      "entropy",
      "snr",
      "mean_gradient_magnitude",
      "median_gradient_magnitude",
      "std_gradient_magnitude",
      "mean_laplace",
      "median_laplace",
      "std_laplace",
      "mean_angle",
      "median_angle",
      "std_angle",
      "sharp_edge_count",
    ]
